# fly.toml app configuration file generated for adventofcode-2024 on 2024-11-26T22:40:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adventofcode-2024'
primary_region = 'arn'

[build]


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
